name: ChaletTest

on: [push, pull_request]

jobs:
  build_version:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        # os: [ubuntu-latest, macos-latest]
        # os: [ubuntu-latest] , windows-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Chalet
      shell: bash
      # run: brew install --cask https://www.chalet-work.space/api/brew/latest/chalet.rb
      run: |
        brew install ninja
        brew install --cask ./chalet.rb

    - name: Cache Chalet
      id: cache-chalet
      uses: actions/cache@v4
      with:
        path: |
          chalet_external
          build
        key: ${ matrix.os }-chaletcache

    - name: Chalet Bundle
      shell: bash
      run: |
        chalet bundle

    - name: Release
      uses: softprops/action-gh-release@v2.0.8
      with:
        files: ./dist/*.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        # token: ${{ secrets.pat }}
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: false        

    # - name: "Upload assets"
    #   uses: softprops/action-gh-release@v2.0.5
    #   with:
    #     files: ./dist/*.zip
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     # token: ${{ secrets.pat }}
    #     # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     name: testing
    #     draft: true
    #     prerelease: false