name: ChaletTest

on: [push, pull_request]

env: 
  CMAKE_CXX_COMPILER_LAUNCHER: ccache

jobs:
  build_version:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        # os: [ubuntu-latest, macos-latest]
        # os: [ubuntu-latest] , windows-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2.14
      with:
        key: ${{ matrix.os }}-ccache

    - name: Install Ninja
      shell: bash
      run: brew install ninja

    - name: Install Chalet
      shell: bash
      run: |
        brew tap chalet-org/chalet
        # brew install --cask chalet
        brew install --cask chalet@dev
        chalet --version

    - name: Cache Chalet
      id: cache-chalet
      uses: actions/cache@v4
      with:
        path: 
          ofChalet/chalet_external
          ofChalet/build
          # chalet_external
          # build
        key: ${ matrix.os }-chaletcache

    # - name: Cache projectGenerator folder
    #   uses: actions/cache@v4
    #   with:
    #     path: '~/projectGenerator'
    #     key: ${{ runner.os }}-pg-${{matrix.cfg.gradle_target}}        

    - name: Chalet Bundle
      shell: bash
      run: |
        chalet bundle

    - name: Release
      uses: softprops/action-gh-release@v2.0.8
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      with:
        files: ./dist/*.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: false        
