name: ChaletTest

on: [push, pull_request]

jobs:
  build_version:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        # os: [ubuntu-latest] , windows-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Chalet
      shell: bash
      run: brew install --cask https://www.chalet-work.space/api/brew/latest/chalet.rb

    - name: Chalet Bundle
      shell: bash
      run: |
        chalet bundle

    - name: "Upload assets"
      uses: softprops/action-gh-release@v2.0.5
      with:
        files: ./dist/*.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        # token: ${{ secrets.pat }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        draft: true
        prerelease: false