name: ChaletTest

on: [push, pull_request]

jobs:
  build_version:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        # os: [ubuntu-latest] , windows-latest

    runs-on: ${{ matrix.os }}

    steps:

    - name: Cache chalet
      id: cache-chalet
      uses: actions/cache@v3
      env:
        cache-name: cache-chalet
      with:
        path: chalet/**
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('chalet/*.md') }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-
    - name: Get Chalet
      if: ${{ steps.cache-libs.outputs.cache-hit != 'true' }}
      uses: dimitre/get-chalet@v2
    - name: Chalet Version
      shell: bash
      run: |
        chalet/build/**/chalet --version

    - name: Is this love?
      shell: bash
      run: |
        chalet/build/**/chalet build
