name: Freetype

on:
  push:
    tags:
      - "v*.*.*"
    # paths:
    #   - freetype/**
    #   - .github/workflows/freetype.yml

env:
  CMAKE_CXX_COMPILER_LAUNCHER: ccache

jobs:
  example_matrix:
    strategy:
      matrix:
        cfg:
          - { os: ubuntu-24.04, platform: linux64 }
          - { os: ubuntu-24.04, platform: arm64 }
          - { os: macos-latest, platform: osx }
          - { os: windows-latest, platform: vs }

    runs-on: ${{ matrix.cfg.os }}
    defaults:
      run:
        working-directory: ./freetype
    steps:
      - uses: actions/checkout@v4

      - name: echo os, platform
        shell: bash
        run: |
          echo ${{ runner.os }} ${{ matrix.cfg.os }} ${{ matrix.cfg.platform }}

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.14
        with:
          key: ${{ runner.os }}-${{ matrix.cfg.platform }}-ccache

      - name: Install Chalet
        uses: jaxxstorm/action-install-gh-release@v1.13.0
        with:
          repo: chalet-org/chalet
          cache: enable
          extension: "\\.zip"
          prerelease: "true"

      - name: Chalet Test / Version
        run: |
          chalet --version

      - name: Get Path
        run: |
          echo $GITHUB_PATH

      - name: Chalet Bundle
        shell: bash
        run: |
          chalet bundle

      - name: LS
        shell: bash
        run: ls -alR

      - name: Rename
        shell: bash
        run: |
          mv dist/freetype.zip dist/oflib_${{ github.ref_name }}_${{ matrix.cfg.platform }}.zip

      - name: Release
        uses: softprops/action-gh-release@v2.2.0
        # if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        if: github.event_name == 'push'
        with:
          files: ./dist/*.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
