name: glfw

on:
  # release:
  # types: [published]
  push:
    # tags:
    # - "*"
    paths:
      - glfw/**
      - .github/workflows/glfw.yml

permissions:
  contents: write

env:
  CMAKE_CXX_COMPILER_LAUNCHER: ccache

jobs:
  example_matrix:
    strategy:
      matrix:
        cfg:
          - { os: ubuntu-24.04, platform: linux64 }
          #- { os: ubuntu-24.04, platform: arm64 }
          - { os: macos-latest, platform: osx }
          - { os: windows-latest, platform: vs }

    runs-on: ${{ matrix.cfg.os }}
    # defaults:
    # run:
    # working-directory: ./${{ github.workflow }}
    steps:
      - uses: actions/checkout@v4

      # - name: echo os, platform       # Linux, ubuntu-24.04 linux64
      #   shell: bash
      #   run: |
      #     echo ${{ runner.os }} ${{ matrix.cfg.os }} ${{ matrix.cfg.platform }}

      - name: Apt
        if: runner.os == 'Linux'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libwayland-dev libxkbcommon-dev libx11-dev
          version: 1.0

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.14
        with:
          key: ${{ runner.os }}-${{ matrix.cfg.platform }}-ccache

      - name: Install Chalet
        uses: jaxxstorm/action-install-gh-release@v1.14.0
        with:
          repo: chalet-org/chalet
          cache: enable
          extension: "\\.zip"
          prerelease: "true"

      # - name: Chalet Test / Version
      #   run: |
      #     chalet --version

      - name: Get Path
        run: |
          echo $GITHUB_PATH

      - name: Chalet Bundle
        shell: bash
        run: |
          cd ${{ github.workflow }}
          chalet bundle

      - name: Rename and Publish Release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        run: |
          rm -rf oflib_${{ matrix.cfg.platform }}_${{ github.workflow }}.zip
          mv ${{ github.workflow }}/dist/${{ github.workflow }}.zip oflib_${{ matrix.cfg.platform }}_${{ github.workflow }}.zip
          ls -alR
          ls -alF *.zip
          # mv dist/${{ github.workflow }}.zip dist/oflib_${{ github.ref_name }}_${{ matrix.cfg.platform }}.zip
          # mv ${{ github.workflow }}/dist/*.zip ../..

          gh release upload vx *.zip --clobber
